timeout 10 # 5 seconds delay
label Linux # boot entry
	kernel /zImage
	fdt /sun8i-h3-nanopi-neo.dtb
    append console=ttyS0,115200 root=PARTUUID=<ROOT_PARTITION_UUID> rootwait rw # can define init=/path/to/init here.
